###
# Database Section
###
database:

  # Schema names to separate the internal, normalized, hard-to-interpret tables from user-friendly views
  schema_names:
    internal: vac
    user_views: jmp

  # How to describe measured samples [this might be different for projects with wafers vs coupons, etc]
  materials:
    # Column name that fully describes a unique piece of material
    full_name: 'LotSample'
    # Other columns that are descriptive of the piece of material
    # Currently, 'Mask' is required to be in this list
    info_columns: ['Lot','Sample','Mask']
    #info_columns: ['Lot','Sample']

meta_reader:
  read_from_filename_regex: ^(?P<LotSample>(?P<Lot>[A-Za-z0-9]+)_(?P<Sample>[A-Za-z0-9]+))
  matload_info_completer: 'datavac.examples.demo1.config:complete_matload_info'

misc_shorthands:
  - &example_csv_reader_template
    function: 'datavac.examples.demo1.example_data:read_csv'

measurement_groups:
  nMOS_IdVg:
    meas_columns: {'FileName':'string'}
    analysis_columns: {'SS [mV/dec]':'float64', 'RonW [ohm.um]':'float64', 'Ron [ohm]':'float64'}
    readers:
      - template: *example_csv_reader_template
        glob: '*_nMOS_IdVg.csv'
    meas_type: ['datavac.measurements.transistor:IdVg',
                {'pol':'n','norm_column':'W [um]','abs_vdsat':1, 'Vgons':{'':1}}]
    connect_to_die_table: False
  pMOS_IdVg:
    meas_columns: {'FileName':'string'}
    analysis_columns: {'SS [mV/dec]':'float64', 'RonW [ohm.um]':'float64', 'Ron [ohm]':'float64'}
    readers:
      - template: *example_csv_reader_template
        glob: '*_pMOS_IdVg.csv'
    meas_type: ['datavac.measurements.transistor:IdVg',
                {'pol':'p','norm_column':'W [um]','abs_vdsat':1, 'Vgons':{'':-1}}]
    connect_to_die_table: False
  inverter_DC:
    meas_columns: {'FileName':'string'}
    analysis_columns: {'max_gain':'float64'}
    readers:
      - template: *example_csv_reader_template
        glob: '*_invs.csv'
    meas_type: 'datavac.measurements.logic_cell:InverterDC'
  logic_oscope:
    meas_columns: {'FileName':'string'}
    analysis_columns: {'truth_table_pass':'bool'}
    readers:
      - template: *example_csv_reader_template
        glob: '*_logic.csv'
    meas_type: 'datavac.measurements.logic_cell:OscopeFormulaLogic'
  ROs:
    meas_columns: {'FileName':'string'}
    analysis_columns: {'t_stage [ps]':'float64'}
    readers:
      - template: *example_csv_reader_template
        glob: '*_ros.csv'
    meas_type: ['datavac.measurements.logic_cell:OscopeRingOscillator',{'stages_col':'stages','div_by_col':'div_by'}]
  divider:
    meas_columns: {'FileName':'string'}
    analysis_columns: {'correct_division':'bool'}
    readers:
      - template: *example_csv_reader_template
        glob: '*_divs.csv'
    meas_type: 'datavac.measurements.logic_cell:OscopeDivider'
  misc_test:
    meas_columns: {'scalar1':'int32'}
    analysis_columns: {}
    readers: []
    connect_to_layout_table: False
    connect_to_die_table: False


masks:
  Mask1:
    arraymap: mask1
array_maps:
  Mask1:
    generator: 'datavac.io.make_diemap:make_fullwafer_diemap'
    args:
      name: DEPRECATETHISPLEASE
      aindex: 30
      bindex: 40
      save_csv: False
